version: "3.9"
services:
  followingservice:
    restart: always
    build:
      context: ./FollowingService
    ports:
      - "8081:8081"
    depends_on:
      - neofollowing

  logservice:
    build:
      context: ./LogService
    ports:
      - "8082:8082"
    depends_on:
      - mongolog

  notificationservice:
    build:
      context: ./NotificationService
    ports:
      - "8083:8083"
      
  postservice:
    build:
      context: ./PostService
    depends_on:
      - postgrespost
    ports:
      - "8084:8084"

  userservice:
    build:
      context: ./UserService
    depends_on:
      - postgresuser
    ports:
      - "8085:8085"

  postgrespost:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: post
    ports:
      - "5432:5432"

  postgresuser:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    ports:
      - "5433:5433"
    command: 
      - "-p 5433"

  mongolog:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"

  neofollowing:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG
    ports:
      - "7474:7474"
      - "7687:7687"
    
  nginx-proxy:
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80


