version: "3.9"
services:
  followingservice:
    build: 
      context: ./FollowingService
    ports:
      - "8081:8080"
  logservice:
    build: 
      context: ./LogService
    ports:
      - "8082:8080"
  notificationservice:
    build: 
      context: ./NotificationService
    ports:
      - "8083:8080"
  postservice:
    build: 
      context: ./PostService
    depends_on:
      - postgrespost
    ports:
      - "8084:8080"
  userservice:
    build: 
      context: ./UserService
    depends_on:
      - postgresuser
    ports:
      - "8085:8080"
  postgrespost:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: post
    ports:
      - "5432:5432"
  postgresuser:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    ports:
      - "5433:5432"
